name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create artifact
        run: |
          mkdir -p out
          zip -r out/biorand-classic-data.zip data
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: biorand-classic-data
          compression-level: 0
          path: out/biorand-classic-data.zip
      - name: Create release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          fail_on_unmatched_files: true
          files: |
            out/biorand-classic-data.zip
