name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create artifact
        run: |
          if TAG=$(git describe --exact-match --tags 2>/dev/null); then
            VERSION=$(echo "$TAG" | sed 's/^v//')
          else
            VERSION=$(git describe --tags --always | sed 's/^v//')
          fi
          echo "$VERSION" > VERSION
          ./create-packs.sh
      - name: Create release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          fail_on_unmatched_files: true
          files: |
            datapacks/*.zip
